# Generated by Django 2.1a1 on 2018-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('ten', models.CharField(blank=True, max_length=50, verbose_name='Tên')),
                ('diachi', models.CharField(blank=True, max_length=50, verbose_name='Địa chỉ')),
                ('SDT', models.CharField(blank=True, max_length=50, verbose_name='Số điện thoại')),
                ('gioitinh', models.CharField(blank=True, max_length=10, verbose_name='giới tính')),
                ('chucvu', models.CharField(blank=True, max_length=20, verbose_name='chức vụ')),
                ('is_supperuser', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
