# Generated by Django 2.1a1 on 2018-07-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_supperuser',
            new_name='is_superuser',
        ),
    ]
